set nocompatible
set nobackup
set nowritebackup
set noswapfile

filetype plugin on

set mouse=a
set ttymouse=sgr
set updatetime=500
set balloondelay=250
set signcolumn=yes
set autoindent
set smartindent
filetype indent on
set backspace=2
set timeoutlen=1000 ttimeoutlen=0

inoremap <silent> <Esc> <Esc>`^
nnoremap <silent> <TAB> :bn<CR>
nnoremap <silent> <S-TAB> :bp<CR>
inoremap <C-e> <C-o>$
inoremap <C-a> <C-o>^

nnoremap <C-p> :Files<cr>
nnoremap <C-b> :Buffers<cr>

nnoremap <leader>r :GOVIMRename<cr>
nnoremap <leader>f :GOVIMReferences<cr>

set signcolumn=number
set background=light
set wildmenu
set laststatus=0
set noeol

set autowriteall
set ai
syntax off

" set guioptions -=m
" set guioptions -=T
" set guioptions -=r
" set guioptions-=L
" set guifont=Go\ 10
" set guicursor+=a:blinkon0

